# Generated by Django 4.2.4 on 2023-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023, verbose_name='name')),
                ('unaccent_name', models.CharField(max_length=1023, verbose_name='unaccent_name')),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actor')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
    ]
